@startuml C4 test

skinparam rectangle {
    RoundCorner 10
}

actor "Документооборот (1C)" as do

rectangle "Kafka Cluster" as kafka

rectangle "Proxy .NET Microservice" as proxy {
    rectangle "REST API" as api
    rectangle "Kafka Worker" as worker
    database "Очередь (БД)\n(Outbox / Staging)" as db
}

do --> api : GET /messages\nPOST /messages
worker --> kafka : poll / send
worker --> db : enqueue messages
api --> db : read messages

@enduml